### ISSUE TITLE
EzYuzu - Yuzu Portable Updater

### ISSUE THREAD

**Issue by buruto** [amakvana/EzYuzu#11] opened 2022-12-28 14:48 UTC
**Describe the bug**

> Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

> The file 'D:\Emulators\YuZu\yuzu-windows-msvc\avcodec-58.dll' already exists.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the directory or folder of 'EzYuzu.exe'
2. Click on 'EzYuzu.exe'
3. Scroll down to 'Yuzu' and click on the "Update" button if clicking on the "Check" button reports that there is a new update.
4. Wait for it to complete and then see error

**Expected behaviour**

"EzYuzu - Yuzu Portable Updater" should just and simply update the Yuzu emulator in the given directory or folder if there is a new update.

**Screenshots**

![image](https://user-images.githubusercontent.com/22644072/209830321-0fc77cd3-2120-4048-bbcb-53603979fcda.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Windows 7]

Windows 10 64 bit

**Additional context**

Error Details:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.IO.IOException: The file 'D:\Emulators\YuZu\yuzu-windows-msvc\avcodec-58.dll' already exists.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
>    at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
>    at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
>    at EzYuzu.frmMain.<>c__DisplayClass15_0.<ProcessYuzu>b__0(Object s, AsyncCompletedEventArgs e)
>    at System.ComponentModel.AsyncCompletedEventHandler.Invoke(Object sender, AsyncCompletedEventArgs e)
>    at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
>    at System.Net.WebClient.DownloadFileOperationCompleted(Object arg)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> EzYuzu
>     Assembly Version: 1.3.0.0
>     Win32 Version: 1.3.0.0
>     CodeBase: file:///D:/Emulators/EzYuzu/EzYuzu.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4566.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.IO.Compression.FileSystem
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
> ----------------------------------------
> System.IO.Compression
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

It doesn't matter if I click on "Continue" or "Quit" buttons. The version of the installed Yuzu is always 1285

**Comment by amakvana** [comment] 2022-12-28 16:17
Thanks for this, can you confirm which directory below is **yuzu.exe** located in (not ezyuzu.exe) on your machine 

1. `D:\Emulators\YuZu\yuzu.exe`
2. `D:\Emulators\YuZu\yuzu-windows-msvc\yuzu.exe`

**Comment by buruto** [comment] 2022-12-29 08:59
> Thanks for this, can you confirm which of the following directories below is **yuzu.exe** _(not ezyuzu.exe)_ located on your machine
> 
> 1. `D:\Emulators\YuZu\yuzu.exe`
> 2. `D:\Emulators\YuZu\yuzu-windows-msvc\yuzu.exe`

1. D:\Emulators\YuZu\yuzu.exe

**Comment by amakvana** [comment] 2022-12-29 09:29
> My personal favorite is to download and install all emulators in D:\Emulators including emulators like pcsx-redux, pcsx2, rpcs3, Citra, ppsspp, Vita3K, Xenia and etc. These that are portable of course.

I also do this with my Emulators too!

> Can I permanently delete yuzu-windows-msvc folder? What is it really used for at all?

`D:\Emulators\YuZu\yuzu-windows-msvc\yuzu.exe` within the `yuzu-windows-msvc` is usually fetched via the maintenance tool, or it could have been manually moved there a while ago. 

Try the following steps for me: 
1. Go to `D:\Emulators\YuZu`, delete the `yuzu-windows-msvc` folder as you have confirmed Yuzu within this directory has not been set up. 
2. Go to `D:\Emulators\YuZu`, if you can also see a folder called `TempUpdate`, delete it.
3. Once you have deleted both folders, rerun EzYuzu, pointing to `D:\Emulators\YuZu` and update again. 

I'm currently in the process of rewriting EzYuzu which should fix some folder naming conflicts

**Comment by buruto** [comment] 2022-12-29 10:34
> > My personal favorite is to download and install all emulators in D:\Emulators including emulators like pcsx-redux, pcsx2, rpcs3, Citra, ppsspp, Vita3K, Xenia and etc. These that are portable of course.
> 
> I also do this with my Emulators too!
> 
> > Can I permanently delete yuzu-windows-msvc folder? What is it really used for at all?
> 
> `D:\Emulators\YuZu\yuzu-windows-msvc\yuzu.exe` within the `yuzu-windows-msvc` is usually fetched via the maintenance tool, or it could have been manually moved there a while ago.
> 
> Try the following steps for me:
> 
> 1. Go to `D:\Emulators\YuZu`, delete the `yuzu-windows-msvc` folder as you have confirmed Yuzu within this directory has not been set up.
> 2. Go to `D:\Emulators\YuZu`, if you can also see a folder called `TempUpdate`, delete it.
> 3. Once you have deleted both folders, rerun EzYuzu, pointing to `D:\Emulators\YuZu` and update again - let me know if this resolves the issue.
> 
> I'm currently in the process of rewriting EzYuzu which should fix some folder naming conflicts

It has updated Yuzu from 1285 to 1287 but EzYuzu still reports that there is a new update when clicking on the Check button and after clicking on the Update button and waiting for EzYuzu to complete the update process Yuzu remains in 1287.

**Comment by amakvana** [comment] 2022-12-29 11:42
> It has updated Yuzu from 1285 to 1287 but EzYuzu still reports that there is a new update when clicking on the Check button and after clicking on the Update button and waiting for EzYuzu to complete the update process Yuzu still remains in 1287.

Looks like the `version` file hasn't been written for some reason. Try this for me

1. Open Command Prompt and enter the following commands below, pressing Enter after each one 

```
pushd "D:\Emulators\YuZu"
(echo 1287)>version
popd
```

> Also since the "Yuzu" option is choosed most of the time every time launching EzYuzu I personally think that the "Yuzu" option should be the default option and not "Dependencies" at all so I don't have to over and over again to open the drop down list and then select "Yuzu" before clicking on the "Check" button and then click on the "Update" button if there is a new update for yuzu every time that I launch EzYuzu.

The rewrite of EzYuzu is going to completely change how this is all handled, it's going to simplify the process and dynamically check the folder which option is required.

Thank you for the feedback! I will look to integrate this within the next version of EzYuzu

**Comment by buruto** [comment] 2022-12-29 11:45
> 

I am software quality assurance and I like to contribute in general.

**Comment by amakvana** [comment] 2022-12-29 23:14
Thanks for the feedback, I have nearly finished rewriting EzYuzu. Once it's compiled, I will attach a copy in here for you to test. It does contain a lot of fixes and some UI changes to simplify things

**Comment by amakvana** [comment] 2022-12-29 23:21
In the meantime, @buruto - can you send me a couple of screenshots containing all of the files and folders inside `D:\Emulators\YuZu`

**Comment by buruto** [comment] 2022-12-30 01:14
> In the meantime, @buruto - can you send me a couple of screenshots containing all of the files and folders inside `D:\Emulators\YuZu`

![image](https://user-images.githubusercontent.com/22644072/210025208-1519cce5-29ce-4d30-86ca-c467e4fd661b.png)

**Comment by buruto** [comment] 2022-12-30 01:42
> Thanks for the feedback, I have nearly finished rewriting EzYuzu. Once it's compiled, I will attach a copy in here for you to test. It does contain a lot of fixes and some UI changes to simplify things

I hope that the "check for updates" feature will work in this new EzYuzu that you are working on and finally report me that there is no new update available when this is really the case.

Your cmd solution did not solve this issue at all but with your first solution to delete both "TempUpdate" and "yuzu-windows-msvc" I could update yuzu to 1288 few hours ago!

**Comment by amakvana** [comment] 2022-12-30 14:17
Thanks for all the feedback,

Okay so within `D:\Emulators\YuZu`, delete the file called `version`

Afterwards, try this:

1. Download the attached file below and unzip it somewhere (lets pick the Desktop).
2. Go to your Desktop and run the newly downloaded EzYuzu.exe file 
3. Once it's loaded, click on `[...]`, browse to `D:\Emulators\YuZu` and select it
4. The button within EzYuzu should change to `Update Yuzu`
5. Click on the button and it should pull Yuzu 1289 (as of now) 

The "Check" option now takes place when you browse and select the Yuzu folder automatically. It will work out if either a `New Install` is required, or to `Update` the existing portable copy within the chosen directory. 

Dependency installs can be toggled within `Options` > `General` > `Update Yuzu` > `Reinstall Visual C++`

[EzYuzu_TestBuild.zip](https://github.com/amakvana/EzYuzu/files/10325075/EzYuzu_TestBuild.zip)

**Comment by buruto** [comment] 2022-12-30 14:36
> @buruto - Thanks for all the feedback so far, I thoroughly appreciate it,
> 
> Okay so within `D:\Emulators\YuZu`, delete the file called `version`
> 
> Afterwards, try this:
> 
> 1. Download the attached file below and unzip it somewhere (lets pick the Desktop).
> 2. Go to your Desktop and run the newly downloaded EzYuzu.exe file
> 3. Once it's loaded, click on `[...]`, browse to `D:\Emulators\YuZu` and select it
> 4. The button text within EzYuzu should change to `Update Yuzu`
> 5. Click on the button and it should pull Yuzu 1289 (as of now)
> 
> The "Check" option now takes place when you browse and select the Yuzu folder automatically. It will work out if either a `New Install` is required, or to `Update` the existing portable copy within the chosen directory.
> 
> Dependency installs can be toggled within `Options` > `General` > `Update Yuzu` > `Reinstall Visual C++`
> 
> [EzYuzu_TestBuild.zip](https://github.com/amakvana/EzYuzu/files/10325075/EzYuzu_TestBuild.zip)

I can use EzYuzu 13.0.0 to install the portable Yuzu and your test build of EzYuzu to both check for updates and update Yuzu if there is a new update.

You not only solved the first problem but even the second problem!

From all the people I was talking to in GitHub issues and discussions, you are definitely the best no doubt.

**Comment by amakvana** [comment] 2022-12-30 15:48
> Yet it doesn't seem that the test build can install a new portable Yuzu because it is a test build to test the check for updates functionality if I understand.

If the folder selected does not contain `yuzu.exe` inside it, EzYuzu will assume that yuzu is not set up in that folder and will pull a new copy. 

Try creating an Empty folder somewhere, then open EzYuzu and browse to the newly created empty folder. EzYuzu will update the button text to say `New Install` and when clicked, will pull a new fresh copy of Yuzu

Try this and let me know.

**Comment by buruto** [comment] 2022-12-30 18:27
> > Yet it doesn't seem that the test build can install a new portable Yuzu because it is a test build to test the check for updates functionality if I understand.
> 
> If the folder selected does not contain `yuzu.exe` inside it, the test build of EzYuzu will assume that Yuzu is not set up in the selected folder and will pull a new copy.
> 
> Try creating an Empty folder somewhere, then open EzYuzu_TestBuild and browse to the newly created empty folder. EzYuzu will update the button text to say `New Install` and when clicked, will pull a new fresh copy of Yuzu
> 
> Try this and let me know.

Neither I know about this nor I thought about doing this.
Your test build can really be used for all Yuzu users who wishes that Yuzu is portable.
But I was not wrong about you. You are really the best.

**Comment by amakvana** [comment] 2022-12-30 18:38
Thanks again for all the feedback! 

I'm just going to do a bit more testing and update all of the documentation, then I will push this out as v1.4.0.0

**Comment by buruto** [comment] 2022-12-30 19:01
> Thanks again for all the feedback!
> 
> I'm just going to do a bit more testing and update all of the documentation, then I will push this out as v1.4.0.0
> 
> Once v1.4.0.0 is released, I will close this

Good to hear.

**Comment by amakvana** [comment] 2022-12-30 23:54
> I also think that EzYuzu should close Yuzu if running before updating Yuzu if there is a new update for Yuzu of course.

This has also been added to v1.4.0.0, credited to you

**Comment by amakvana** [comment] 2022-12-30 23:55
Closed - Fixed in v1.4.0.0
https://github.com/amakvana/EzYuzu/releases/latest

**Closed by amakvana** 2022-12-30 23:55 UTC
