### ISSUE TITLE
New version of ezyuzu crashes on started

### ISSUE THREAD

**Issue by Metroid-Prime** [amakvana/EzYuzu#43] opened 2023-10-09 05:57 UTC
**Describe the bug**
ezyuzu crashes with error

**To Reproduce**
1. Launch ezyuzu (16.2.0)
2. Observe error:
[code]See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'D:\Games\Nintendo Switch\Yuzu\Yuzu Early Access\yuzu.exe' with working directory 'D:\Games\Nintendo Switch\EzYuzu'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at EzYuzu.FrmMain.FrmMain_LoadAsync(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Private.CoreLib.dll
----------------------------------------
EzYuzu
    Assembly Version: 1.6.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.Specialized.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 8.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Http
    Assembly Version: 8.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Http
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Http.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 8.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.dll
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 8.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 8.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 8.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Linq.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.Concurrent.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.Tracing.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Memory.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.Loader.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ObjectModel.dll
----------------------------------------
System.Text.Json
    Assembly Version: 8.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Security.Claims.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 8.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.Intrinsics.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Private.Uri.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Reflection.Primitives.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.NonGeneric.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.Process.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Primitives.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.ThreadPool.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Security.Cryptography.dll
----------------------------------------
System.Net.Quic
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Quic.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.NameResolution.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************
[/code]

**Expected behavior**
Not crash :)

**Desktop (please complete the following information):**
 -Windows 10 LTSC 2021  OS Build 19044.3448

16.1.0 does not crash.

**Comment by amakvana** [comment] 2023-10-09 06:53
Thanks for opening up the issue!

Please would you be able to confirm the following for me please:

1. Which options under `Options` > `General` > `Update Yuzu` you have checked?
2. At which stage does EzYuzu crash?

**Comment by Gwouigwoui** [comment] 2023-10-10 12:31
Can confirm the issue when running through the GUI. The faulty option is "launch Yuzu after update", the others work as intended it seems.

**Comment by amakvana** [comment] 2023-10-10 12:48
> Can confirm the issue when running through the GUI. The faulty option is "launch Yuzu after update", the others work as intended it seems.

Thanks for confirming! Is this after you click on Update? Or when you initially first load EzYuzu?

**Comment by amakvana** [comment] 2023-10-10 13:05
@Metroid-Prime @Gwouigwoui try the test build attached and let me know if the same issue persists.

Before you run it, delete the following two files:
1. `version` inside the folder where `yuzu.exe` resides in
2. EzYuzu.settings.json 

After those have been deleted, open EzYuzu, set your preferences as before, update Yuzu and see if the issue persists 
[EzYuzu_TestBuild.zip](https://github.com/amakvana/EzYuzu/files/12857504/EzYuzu_TestBuild.zip)

**Comment by Gwouigwoui** [comment] 2023-10-10 17:43
I can't get the test build to start. A bit more info: the problem only appears when Yuzu is not being updated. When there's an update then Yuzu is correctly launched after the update. When there's no update, however, is when the issue appears.
   Le mardi 10 octobre 2023 à 09:05:59 UTC−4, Akash Makvana ***@***.***> a écrit :  
 
 


@Metroid-Prime @Gwouigwoui try the test build attached and let me know if the same issue persists.

Before you run it, delete the following two files:
   
   - version inside the folder where yuzu.exe resides in
   - EzYuzu.settings.json

After those have been deleted, open EzYuzu, set your preferences as before, update Yuzu and see if the issue persists
EzYuzu_TestBuild.zip

**Comment by amakvana** [comment] 2023-10-10 18:00
Cheers for that! Think I've found the issue, try the build attached to this instead and follow the same steps as my previous reply 

[EzYuzu_TestBuild_2.zip](https://github.com/amakvana/EzYuzu/files/12860403/EzYuzu_TestBuild_2.zip)

**Comment by Gwouigwoui** [comment] 2023-10-10 18:21
All good now!
   Le mardi 10 octobre 2023 à 14:00:42 UTC−4, Akash Makvana ***@***.***> a écrit :  
 
 


Cheers for that! Think I've found the issue, try the build attached to this instead and follow the same steps as my previous reply

EzYuzu_TestBuild_2.zip

**Comment by amakvana** [comment] 2023-10-10 20:10
Thanks for confirming! Will push the changes soon

**Comment by amakvana** [comment] 2023-10-10 20:25
Closed - Fixed in v1.6.2.1
https://github.com/amakvana/EzYuzu/releases/latest

**Closed by amakvana** 2023-10-10 20:25 UTC
Labels: bug, question
